// <auto-generated />
using System;
using DoctorCrm.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DoctorCrm.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008112942_PartPaymentsAndBalances")]
    partial class PartPaymentsAndBalances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoctorCrm.Api.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.BillingAccount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BillingCycleAnchor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("billing_cycle_anchor");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<string>("CardBrand")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("card_brand");

                    b.Property<string>("CardLast4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("card_last4");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTime?>("FinalRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("final_retry_at");

                    b.Property<string>("FinalRetryError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("final_retry_error");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTime?>("OverdueSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("overdue_since");

                    b.Property<long?>("PlanAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_amount");

                    b.Property<string>("PlanCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("plan_currency");

                    b.Property<string>("PlanInterval")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("plan_interval");

                    b.Property<int>("PlanIntervalCount")
                        .HasColumnType("integer")
                        .HasColumnName("plan_interval_count");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<string>("SubscriptionStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("subscription_status");

                    b.Property<long?>("UnpaidAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("unpaid_amount");

                    b.Property<string>("UnpaidCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("unpaid_currency");

                    b.Property<string>("UnpaidInvoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unpaid_invoice_id");

                    b.Property<string>("UnpaidInvoiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("unpaid_invoice_url");

                    b.Property<DateTime?>("UnpaidSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unpaid_since");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_billing_accounts");

                    b.ToTable("billing_accounts", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.BillingSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("FirstPaymentDue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_payment_due");

                    b.Property<int>("GraceDays")
                        .HasColumnType("integer")
                        .HasColumnName("grace_days");

                    b.Property<string>("PriceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("price_id");

                    b.Property<string>("SecretKeyHint")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("secret_key_hint");

                    b.Property<string>("SecretKeyProtected")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("secret_key_protected");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("WebhookSecretProtected")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("webhook_secret_protected");

                    b.HasKey("Id")
                        .HasName("pk_billing_settings");

                    b.ToTable("billing_settings", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_paid");

                    b.Property<decimal>("Balance")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("balance");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<string>("CancellationNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_note");

                    b.Property<int?>("CancellationReasonId")
                        .HasColumnType("integer")
                        .HasColumnName("cancellation_reason_id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("ConsultationCharge")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("consultation_charge");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<string>("DoctorNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("doctor_notes");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<DateOnly?>("NextTreatmentDate")
                        .HasColumnType("date")
                        .HasColumnName("next_treatment_date");

                    b.Property<int?>("NextTreatmentId")
                        .HasColumnType("integer")
                        .HasColumnName("next_treatment_id");

                    b.Property<DateTime?>("NoShowAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("no_show_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int?>("OriginalBookingId")
                        .HasColumnType("integer")
                        .HasColumnName("original_booking_id");

                    b.Property<DateTime?>("RescheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rescheduled_at");

                    b.Property<string>("Source")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CancellationReasonId")
                        .HasDatabaseName("ix_bookings_cancellation_reason_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_bookings_created_by_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bookings_customer_id");

                    b.HasIndex("NextTreatmentId")
                        .HasDatabaseName("ix_bookings_next_treatment_id");

                    b.HasIndex("OriginalBookingId")
                        .HasDatabaseName("ix_bookings_original_booking_id");

                    b.HasIndex("BookingDate", "StartTime")
                        .HasDatabaseName("ix_bookings_booking_date_start_time");

                    b.HasIndex("CustomerId", "Balance")
                        .HasDatabaseName("ix_bookings_customer_id_balance")
                        .HasFilter("balance > 0");

                    b.HasIndex("DoctorId", "BookingDate")
                        .HasDatabaseName("ix_bookings_doctor_id_booking_date");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.BookingTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("integer")
                        .HasColumnName("treatment_id");

                    b.HasKey("Id")
                        .HasName("pk_booking_treatments");

                    b.HasIndex("TreatmentId")
                        .HasDatabaseName("ix_booking_treatments_treatment_id");

                    b.HasIndex("BookingId", "TreatmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_treatments_booking_id_treatment_id");

                    b.ToTable("booking_treatments", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CalendarBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_calendar_blocks");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_calendar_blocks_created_by_id");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("ix_calendar_blocks_start_date_end_date");

                    b.ToTable("calendar_blocks", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CancellationReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cancellation_reasons");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_cancellation_reasons_display_order");

                    b.ToTable("cancellation_reasons", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CaptureClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<string>("ExtensionVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extension_version");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_capture_clients");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_capture_clients_client_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_capture_clients_created_by_id");

                    b.ToTable("capture_clients", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CaptureFieldConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("custom_field_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("field_key");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_capture_field_configurations");

                    b.HasIndex("CustomFieldId")
                        .HasDatabaseName("ix_capture_field_configurations_custom_field_id");

                    b.HasIndex("FieldKey")
                        .IsUnique()
                        .HasDatabaseName("ix_capture_field_configurations_field_key");

                    b.ToTable("capture_field_configurations", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CustomField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("field_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_custom_fields");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_custom_fields_display_order");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_fields_key");

                    b.ToTable("custom_fields", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CustomFieldOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("custom_field_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("pk_custom_field_options");

                    b.HasIndex("CustomFieldId", "DisplayOrder")
                        .HasDatabaseName("ix_custom_field_options_custom_field_id_display_order");

                    b.ToTable("custom_field_options", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("InstagramName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("instagram_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateOnly?>("LastContactDate")
                        .HasColumnType("date")
                        .HasColumnName("last_contact_date");

                    b.Property<int?>("LeadSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_source_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextFollowUpDate")
                        .HasColumnType("date")
                        .HasColumnName("next_follow_up_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("secondary_phone");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WhatsAppNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("whats_app_number");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_customers_assigned_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_customers_created_at");

                    b.HasIndex("InstagramName")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_instagram_name")
                        .HasFilter("instagram_name IS NOT NULL");

                    b.HasIndex("LeadSourceId")
                        .HasDatabaseName("ix_customers_lead_source_id");

                    b.HasIndex("NextFollowUpDate")
                        .HasDatabaseName("ix_customers_next_follow_up_date");

                    b.HasIndex("StageId")
                        .HasDatabaseName("ix_customers_stage_id");

                    b.HasIndex("WhatsAppNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_whats_app_number")
                        .HasFilter("whats_app_number IS NOT NULL");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CustomerCustomFieldValue", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("CustomFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("custom_field_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("CustomerId", "CustomFieldId")
                        .HasName("pk_customer_custom_field_values");

                    b.HasIndex("CustomFieldId")
                        .HasDatabaseName("ix_customer_custom_field_values_custom_field_id");

                    b.ToTable("customer_custom_field_values", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CustomerTreatment", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("integer")
                        .HasColumnName("treatment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("CustomerId", "TreatmentId")
                        .HasName("pk_customer_treatments");

                    b.HasIndex("TreatmentId")
                        .HasDatabaseName("ix_customer_treatments_treatment_id");

                    b.ToTable("customer_treatments", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SystemKey")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("system_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lead_sources");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_lead_sources_display_order");

                    b.HasIndex("SystemKey")
                        .IsUnique()
                        .HasDatabaseName("ix_lead_sources_system_key")
                        .HasFilter("system_key IS NOT NULL");

                    b.ToTable("lead_sources", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_payments_booking_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_payments_created_at");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_payments_created_by_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_payments_customer_id");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_payments_payment_method_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payment_methods");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_payment_methods_display_order");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_key");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SystemKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("system_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stages");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_stages_display_order");

                    b.HasIndex("SystemKey")
                        .IsUnique()
                        .HasDatabaseName("ix_stages_system_key");

                    b.ToTable("stages", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_system_settings");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_treatments");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_treatments_display_order");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_treatments_name");

                    b.ToTable("treatments", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPlatformOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_platform_owner");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.AuditLog", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Booking", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.CancellationReason", "CancellationReason")
                        .WithMany()
                        .HasForeignKey("CancellationReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_cancellation_reasons_cancellation_reason_id");

                    b.HasOne("DoctorCrm.Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bookings_users_created_by_id");

                    b.HasOne("DoctorCrm.Api.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_customers_customer_id");

                    b.HasOne("DoctorCrm.Api.Entities.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_users_doctor_id");

                    b.HasOne("DoctorCrm.Api.Entities.Treatment", "NextTreatment")
                        .WithMany()
                        .HasForeignKey("NextTreatmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_treatments_next_treatment_id");

                    b.HasOne("DoctorCrm.Api.Entities.Booking", "OriginalBooking")
                        .WithMany()
                        .HasForeignKey("OriginalBookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_bookings_original_booking_id");

                    b.Navigation("CancellationReason");

                    b.Navigation("Customer");

                    b.Navigation("Doctor");

                    b.Navigation("NextTreatment");

                    b.Navigation("OriginalBooking");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.BookingTreatment", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.Booking", "Booking")
                        .WithMany("Treatments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_treatments_bookings_booking_id");

                    b.HasOne("DoctorCrm.Api.Entities.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_treatments_treatments_treatment_id");

                    b.Navigation("Booking");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CalendarBlock", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_calendar_blocks_users_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CaptureClient", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_capture_clients_users_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CaptureFieldConfiguration", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.CustomField", "CustomField")
                        .WithMany()
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_capture_field_configurations_custom_fields_custom_field_id");

                    b.Navigation("CustomField");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CustomFieldOption", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.CustomField", "CustomField")
                        .WithMany("Options")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_field_options_custom_fields_custom_field_id");

                    b.Navigation("CustomField");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Customer", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customers_users_assigned_user_id");

                    b.HasOne("DoctorCrm.Api.Entities.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customers_lead_sources_lead_source_id");

                    b.HasOne("DoctorCrm.Api.Entities.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_stages_stage_id");

                    b.Navigation("AssignedUser");

                    b.Navigation("LeadSource");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CustomerCustomFieldValue", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.CustomField", "CustomField")
                        .WithMany()
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_custom_field_values_custom_fields_custom_field_id");

                    b.HasOne("DoctorCrm.Api.Entities.Customer", "Customer")
                        .WithMany("CustomFieldValues")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_custom_field_values_customers_customer_id");

                    b.Navigation("CustomField");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CustomerTreatment", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.Customer", "Customer")
                        .WithMany("Treatments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_treatments_customers_customer_id");

                    b.HasOne("DoctorCrm.Api.Entities.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_treatments_treatments_treatment_id");

                    b.Navigation("Customer");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Payment", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_bookings_booking_id");

                    b.HasOne("DoctorCrm.Api.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_users_created_by_id");

                    b.HasOne("DoctorCrm.Api.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_customers_customer_id");

                    b.HasOne("DoctorCrm.Api.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_payment_methods_payment_method_id");

                    b.Navigation("Booking");

                    b.Navigation("CreatedBy");

                    b.Navigation("Customer");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.RolePermission", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("DoctorCrm.Api.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.UserRole", b =>
                {
                    b.HasOne("DoctorCrm.Api.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("DoctorCrm.Api.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Booking", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.CustomField", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Customer", b =>
                {
                    b.Navigation("CustomFieldValues");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DoctorCrm.Api.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
